### ISSUE TITLE
add Link for contributors gh page in README .

### ISSUE THREAD

**Issue by saurabhmehta1601** [saurabhmehta1601/Niramaya-frontend#69]

**Comment by saurabhmehta1601** [comment]
The link for contributor page is https://saurabhmehta1601.github.io/Niramaya-frontend/ . 
put some headline like see our contributors and refere the link

**Comment by srkds** [comment]
Hi there,

something like this?
in the contributor's section? 
![Ss](https://user-images.githubusercontent.com/61644078/139573803-f696ab1f-4bd6-4746-94ae-25409003b999.png)

**Comment by saurabhmehta1601** [comment]
Actually I have a dedicated github page for contributors . You just have to put link given above with some heading like our contributor but if you can directly put contributors in README then that's also great :100:
